<?php

namespace Tests;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Support\Facades\Artisan;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication, DatabaseMigrations;

    public function setUp()
    {
//        parent::setUp(); // TODO: Change the autogenerated stub
        parent::setUp();
        Artisan::call('db:seed');
    }

    protected function signIn($user = null){
        $user = $user ?: create('App\User');
        $this->actingAs($user);
        return $this;
    }
}
